version: '3.8'

services:
  db:
    image: postgres:14
    container_name: route-manager-db
    environment:
      POSTGRES_DB: studs
      POSTGRES_USER: s408402
      POSTGRES_PASSWORD: aezx5k0IS9wfRtkM
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    image: minio/minio:latest
    container_name: route-manager-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "4898:9000"
      - "4899:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4898/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  pgdata:
  minio_data: